- hosts: GNCASNHL07926, GNCASNHL07927
  gather_facts: yes
  tasks:
    - name: Coletar hostname
      set_fact:
        all_hostnames: "{{ hostvars[host]['ansible_hostname'] }}" for host in groups['hosts'] | list }}"
