- hosts: GNCASNHL07926,GNCASNHL07927
  gather_facts: false
  tasks:
    - shell: hostname
      register: weblogic_scraping
      changed_when: false
    - name: Enviar e-mail com o relatório
      mail:
        host: smtp.gmail.com
        port: 587
        username: david.sf026@gmail.com
        password: "{{ smtppwd }}"
        from: david.sf026@gmail.com
        to: david.sf026@gmail.com
        subject: Planilha Coleta de Dados Hosts WebLogic
        body: |
          host,domain-version,machines,datasources
          {% for host in ansible_play_hosts %}
          {{ hostvars[host]['weblogic_scraping'].stdout }}
          {% endfor %}
      run_once: yes
