- name: Pegar hostname dos hosts GNCASNHL07926 e GNCASNHL07927
  hosts: GNCASNHL07926,GNCASNHL07927
  gather_facts: no

  tasks:
    - set_fact:
        hostnames: "{{ hostnames|default([]) + [inventory_hostname] }}"
- name: Exibir lista de hostnames
  hosts: localhost
  gather_facts: no

  tasks:
    - debug:
        var: hostnames
