---
- name: gather data
  hosts: GNCASNHL07926, GNCASNHL07927
  gather_facts: false
  tasks:
  - name: Get current status  
    shell: echo "123"
    register: app_status
  
  - name: Create an empty fact one time and locally to store our summary email text
    set_fact: 
      Summary: " "
      cacheable: yes
    run_once: true
    delegate_to: localhost

  - name: Populate the fact with more information for each host we check the status on 
    set_fact:
      Summary: " {{ Summary }}  {{ app_status.stdout_lines }} "
      cacheable: yes
    delegate_to: localhost

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
    delegate_to: localhost
