- hosts: GNCASNHL07926,GNCASNHL07927
  gather_facts: false
  tasks:
    - shell: hostname
      register: date_res
      changed_when: false
    - name: Enviar e-mail com o relatório
      mail:
        host: smtp.gmail.com
        port: 587
        username: david.sf026@gmail.com
        password: "{{ smtppwd }}"
        from: david.sf026@gmail.com
        to: david.sf026@gmail.com
        subject: Relatório de hostname
        body: |
          hostnames
          {% for host in ansible_play_hosts %}
          {{ hostvars[host]['date_res'].stdout }}
          {% endfor %}
      run_once: yes
