- name: Pegar hostname dos hosts GNCASNHL07926 e GNCASNHL07927
  hosts: GNCASNHL07926,GNCASNHL07927
  gather_facts: no

  tasks:
    - shell: "hostname"
      register: hostname_output
    - set_fact:
        hostnames: "{{ hostnames|default([]) + [hostname_output.stdout.strip()] }}"
    - debug:
        var: hostnames
