- hosts: localhost
  gather_facts: false
  tasks:
    - name: Adding localhost
      add_host:
        hostname: "{{ item }}"
        groups: weblogic
      loop: "{{ guestname }}"

- hosts: weblogic
  tasks:
    - name: Executar script de coleta de cat /etc/os/release
      shell: |
        #!/bin/bash
        cat /etc/os-release
      register: script_output

    - name: Concatenar saídas do script de coleta
      set_fact:
        cacheable: true
        all_output: "{{ all_output|default([]) + script_output.stdout_lines }}"
    - debug:
      msg: all_output

- hosts: localhost
  tasks:
  - name: Mostrar na tela o all_output
    debug:
      var: all_output
