- hosts: localhost
  gather_facts: false
  tasks:
    - name: Adding localhost
      add_host:
        hostname: "{{ item }}"
        groups: weblogic
      loop: "{{ guestname }}"

- name: Analisar arquivo /etc/os-release
  hosts: machines
  tasks:
    - name: Obter conteúdo do arquivo /etc/os-release
      shell: cat /etc/os-release
      register: os_release

    - name: Gerar relatório
      set_fact:
        report: "{{ report | default([]) + [{'hostname': inventory_hostname, 'os_release': os_release.stdout}] }}"

  handlers:
    - name: Enviar relatório por e-mail
      mail:
        host: smtp.gmail.com
        port: 587
        username: david.sf026@gmail.com
        password: {{ smtppwd }}
        from: david.sf026@gmail.com
        to: david.sf026@gmail.com
        subject: Relatório de OS Release
        body: "{{ report }}"
      notify: Enviar relatório

  - name: Enviar relatório
    meta: no_log: true
