---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Adding localhost
      add_host:
        hostname: "{{ item }}"
        groups: weblogic
      loop: "{{ guestname }}"
- hosts: weblogic
  gather_facts: false
  tasks:
    - name: Buscando dados desejados através de bash script
      command: bash
      args:
        stdin: |
          #!/bin/bash
          whoami > /tmp/oi.txt
      changed_when: false
