- hosts: localhost
  tasks:
    - name: Executar script de coleta de informações do WebLogic
      shell: |
        #!/bin/bash
        hostname
      register: script_output

    - name: Concatenar saídas do script de coleta
      set_fact:
        all_output: "{{ all_output|default([]) + script_output.stdout_lines }}"

    - name: Exibir saída do script de coleta de informações do WebLogic
      debug:
        var: all_output
