- hosts: localhost
  gather_facts: false
  tasks:
    - name: Adding localhost
      add_host:
        hostname: "{{ item }}"
        groups: weblogic
      loop: "{{ guestname }}"

- name: Coletar hostname das máquinas
  hosts: weblogic
  tasks:
    - name: Obter hostname da máquina
      shell: hostname
      register: hostname_output

    - name: Consolidar hostnames em um único arquivo
      lineinfile:
        line: "{{ hostname_output.stdout }}"
        path: /tmp/hostname_report.txt

- name: Enviar relatório por e-mail
  hosts: localhost
  tasks:
    - name: Ler o arquivo de relatório
      slurp:
        src: /tmp/hostname_report.txt
      register: report_output

    - name: Enviar e-mail com o relatório
      mail:
        host: smtp.gmail.com
        port: 587
        username: david.sf026@gmail.com
        password: {{ smtppwd }}
        from: david.sf026@gmail.com
        to: david.sf026@gmail.com
        subject: Relatório de hostname
        body: "{{ report_output.content | b64decode }}"
