- name: Armazenar "Hello World" em um register e enviar o arquivo para o localhost
  hosts: GNCASNHL07925
  tasks:
    - name: Escrever "Hello World" na saída padrão
      debug:
        msg: "Hello World"
      register: hello_register

    - name: Exibir o conteúdo do register
      debug:
        var: hello_register

    - name: Armazenar o conteúdo do register em um arquivo
      copy:
        content: "{{ hello_register.msg }}"
        dest: "/tmp/hello.txt"

    - name: Copiar o arquivo para o localhost
      copy:
        src: "/tmp/hello.txt"
        dest: "/tmp/hello.txt"
        delegate_to: localhost
