- hosts: localhost
  gather_facts: false
  tasks:
    - name: Adding localhost
      add_host:
        hostname: "{{ item }}"
        groups: weblogic
      loop: "{{ guestname }}"
    - name: Set empty all_output variable
      set_fact:
        all_output: []

- hosts: weblogic
  tasks:
    - name: Executar script de coleta de informações do WebLogic
      shell: |
        #!/bin/bash
        domain_home=$(cat /home/david/workdir/ssm/ps.txt |grep nodemanager | grep -o "Dweblogic.RootDirectory=.*" | cut -d "=" -f 2 | sed 's/ -.*//g' | grep /)
        config_xml=$(cat "$domain_home"/config/config.xml)
        jdbc_xml=$(cat "$domain_home"/config/jdbc/*jdbc*.xml)
        domain_version=$(echo "$config_xml" | grep -oE '<domain-version>[^<]+</domain-version>' | sed -E 's/<\/?domain-version>//g')
        machines=$(echo "$config_xml" | grep -o '<machine>[^<]*</machine>' | sed -E 's/<machine>([^<]+)<\/machine>/\1/' | awk '!seen[$0]++' | grep -vE '^ *$' | tr '\n' ',' | sed 's/,$//')
        datasources=$(echo "$jdbc_xml" | grep -o '<url>[^<]*</url>' | grep jdbc | sed -E 's/<url>([^<]+)<\/url>/\1/' | awk '!seen[$0]++' | grep -vE '^ *$' | tr '\n' ',' | sed 's/,$//')
        output="$(hostname),$domain_version,\"$machines\",\"$datasources\""
        echo "$header$output"
      register: script_output

    - name: Concatenar saídas do script de coleta
      set_fact:
        all_output: "{{ all_output + script_output.stdout_lines }}"

- hosts: localhost
  tasks:
    - debug:
        var: all_output
