- name: Armazenar "Hello World" em um register e enviar o arquivo para outro host
  hosts: GNCASNHL07923
  tasks:
    - name: Escrever "Hello World" na saída padrão
      debug:
        msg: "Hello World"
      register: hello_register

    - name: Exibir o conteúdo do register
      debug:
        var: hello_register

    - name: Armazenar o conteúdo do register em um arquivo
      copy:
        content: "{{ hello_register.stdout }}"
        dest: "/tmp/hello.txt"

    - name: Enviar o arquivo para outro host
      copy:
        src: "/tmp/hello.txt"
        dest: "/tmp/hello.txt"
        remote_src: yes
      delegate_to: localhost
