- hosts: localhost
  gather_facts: false
  tasks:
    - name: Adding localhost
      add_host:
        hostname: "{{ item }}"
        groups: weblogic
      loop: "{{ guestname }}"
    - name: Set empty all_output variable
      set_fact:
        all_output: []

- hosts: weblogic
  tasks:
    - name: Executar script de coleta de cat /etc/os/release
      shell: |
        #!/bin/bash
        cat /etc/os-release
      register: script_output

    - name: Concatenar saídas do script de coleta
      set_fact:
        all_output: "{{ all_output|default([]) + script_output.stdout_lines }}"

    - name: Mostrar na tela o all_output
      debug:
        var: all_output

- hosts: localhost
  tasks:
    - name: Mostrar na tela o all_output
      debug:
        var: all_output

