- hosts: localhost
  tasks:
    - name: Executar script de coleta de informações do WebLogic
      shell: |
        #!/bin/bash
        echo "oi"
      register: script_output

    - name: Concatenar saídas do script de coleta
      set_fact:
        all_output: "{{ all_output|default([]) + script_output.stdout_lines }}"

    - name: Salvar output em um arquivo
      copy:
        content: "{{ all_output|join('\n') }}"
        dest: "/tmp/output.txt"

    - name: Configurar output.txt como Artifact
      tower_job_artifact:
        job_id: "{{ tower_job_id }}"
        artifact: "/tmp/output.txt"
